export type UiLocale = "en" | "zh-CN";

export const UI_LOCALES = ["en", "zh-CN"] as const;

export const uiCopy = {
  en: {
    htmlLang: "en",
    nav: {
      today: "Today",
      plan: "Plan",
      materials: "Materials",
      practice: "Practice",
      review: "Review",
      import: "Import",
      library: "Library",
    },
    common: {
      importThesis: "Import a thesis",
      noThesis: "No thesis yet",
      noActiveThesis: "No active thesis. Please import a thesis first.",
      importFirst: "Import a thesis first.",
      none: "—",
    },
    home: {
      noThesisBody: "Import a thesis to start preparing for your viva.",
      recommendedNext: "Recommended next:",
      fullPlan: "Full plan →",
      dayOf: (day: number, total: number) => `Day ${day} of ${total}`,
      verified: "Verified",
      needsReview: "Needs review",
      practiceRuns: "Practice runs",
      toReview: "To review",
      evidenceSummary: (evidence: number, prep: number) => `${evidence} evidence units · ${prep} prep items · `,
      librarySettings: "library & settings",
    },
    actions: {
      generatePrepPack: "Generate a prep pack",
      setupAi: "Set up AI to generate a prep pack",
      startPractice: "Start practising",
      reviewWeak: (count: number) => `Review ${count} weak ${count === 1 ? "spot" : "spots"}`,
      practiceAnother: "Practise another question",
    },
    materials: {
      title: "Materials",
      empty: "No prep items yet. Click Generate Prep Pack to create your study materials.",
      edit: "Edit",
      generate: "Generate Prep Pack",
      generating: "Generating...",
      generated: (count: number) => `Generated ${count} items.`,
      verifiedNote: (basis: string, value: string) =>
        `Verified: the ${basis || "evidence"}${value ? ` (${value})` : ""} is grounded in your thesis. The surrounding wording is AI-generated.`,
    },
    importPage: {
      title: "Import a thesis",
      body: "Paste Markdown/text or upload a PDF. Importing replaces the current active thesis.",
      titleField: "Title",
      source: "Source",
      markdown: "Markdown",
      plainText: "Plain text",
      pdf: "PDF",
      pdfFile: "PDF file",
      content: "Content",
      submit: "Import",
      submitting: "Importing...",
    },
    editItem: {
      title: "Edit prep item",
      note: (type: string) => `${type} - re-validated against its bound evidence on save.`,
      boundEvidence: "Bound evidence",
      noEvidence: "No evidence bound - this item cannot be verified.",
      claim: "Claim",
      fixedClaim: "Claim (fixed):",
      supportingQuote: "Supporting quote (must appear verbatim in the bound evidence above)",
      value: "Value",
      unit: "Unit",
      save: "Save & re-validate",
      cancel: "Cancel",
    },
    practice: {
      title: "Practice",
      begin: "Generate a question to begin.",
      questionType: "Question type",
      topic: "Topic (optional)",
      topicPlaceholder: "e.g. methodology, sample size",
      generateQuestion: "Generate question",
      generating: "Generating...",
      question: (kind: string) => `${kind} question`,
      yourAnswer: "Your answer:",
      weakReasons: "Why the weak dimensions scored low",
      diagnosis: "Diagnosis",
      rewrite: "Suggested rewrite",
      followUps: "Follow-up questions",
      record: "🎤 Record answer",
      stop: "■ Stop",
      transcribing: "Transcribing...",
      answerPlaceholder: "Type your answer...",
      answerPlaceholderStt: "Type your answer - or record above and edit the transcript...",
      submit: "Submit answer",
      scoring: "Scoring...",
      recordUnsupported: "Recording is not supported in this browser - type your answer instead.",
      noAudio: "No audio was captured.",
      tooLong: "Recording is too long - keep it under ~10 MB.",
      transcribeFail: "Could not transcribe the recording. Please try again.",
      micFail: "Could not access the microphone.",
      speechUnsupported: "Speech recognition isn't supported in this browser - type your answer instead.",
      speechError: (error?: string) => `Speech recognition error${error ? `: ${error}` : ""}.`,
      speechStartFail: "Could not start speech recognition.",
    },
    review: {
      title: "Review queue",
      headline: "Review",
      body: "Dimensions scored 2 or below - worth another pass.",
      practiceMore: "Practice more →",
      empty: "Nothing to review. Answer some practice questions first, or you are all caught up.",
    },
    plan: {
      title: "Training plan",
      importBody: "Import a thesis to start your plan.",
      buildFor: (title: string) => `Build a local study schedule for "${title}".`,
      days: "Days",
      generate: "Generate plan",
      aiOn: "AI is on - generating sends your thesis title, section names, and a short progress summary to your configured AI provider.",
      aiOff: "AI is off - you will get a standard N-day template. Nothing is sent.",
      daySummary: (name: string, day: number, total: number) => `${name} · day ${day} of ${total}`,
      doubleCheck: "This is a study schedule - double-check any specifics against your materials and prep pack.",
      today: "Today",
      noPlan: "No training plan yet",
      noPlanBody: "Choose a length and generate a plan to anchor your daily prep.",
      ai: "AI",
      static: "Static",
    },
    library: {
      title: "Library & settings",
      activeThesis: "Active thesis",
      titleField: "Title",
      author: "Author",
      source: "Source",
      imported: "Imported",
      noImported: "No thesis imported.",
      importOne: "Import one",
      yourTheses: "Your theses",
      active: "Active",
      makeActive: "Make active",
      aiPrivacy: "AI & privacy",
      aiLabel: "AI examiner / judge / prep generation:",
      sttLabel: "Speech-to-text:",
      aiEnabled:
        "enabled - content is sent to your configured AI Gateway provider: generating a prep pack sends the thesis title and its bound evidence; generating a question or scoring an answer sends the question text, the relevant bound evidence, and your answer (typed or transcribed); a follow-up also includes the previous question and answer.",
      aiGatewayMissing: "off - a provider key is set but AI_GATEWAY_API_KEY is not, so nothing is sent.",
      aiDisabled: "disabled - no thesis text or answers are sent anywhere.",
      sttOff: "off - no audio is captured or sent.",
      sttBrowser:
        "browser - your browser's built-in continuous recognition transcribes your voice. Depending on the browser, audio may be sent to the browser vendor's service. No audio passes through this app.",
      sttGoogle:
        "Google Cloud - recorded audio is sent to Google Cloud Speech-to-Text for transcription. Answers over ~1 minute are not supported here.",
      localData: "Your thesis, database, and recordings are always stored locally.",
      nothingLeaves: " In this configuration, nothing leaves your machine.",
      accuracy: "Content accuracy",
      unsafe: "Unsafe",
      draft: "Draft",
      accuracyBody:
        "Only prep items whose key facts are deterministically provable against their bound evidence are marked verified. Everything else stays needs review, unsafe, or draft - the app never presents an unverified claim as fact.",
      importStats: "Import a thesis to see accuracy stats.",
    },
    labels: {
      statuses: { verified: "verified", needs_review: "needs review", unsafe: "unsafe", draft: "draft" },
      itemTypes: {
        digest: "digest",
        key_number: "key number",
        qa: "Q&A",
        hostile: "hostile question",
        hostile_question: "hostile question",
        theory_card: "theory card",
        citation_card: "citation card",
      },
      support: { numeric: "number", exact_quote: "quote", existence: "", llm_suggested: "" },
      questionKinds: { random: "random", cross_section: "cross-section", hostile: "hostile", boundary: "boundary", by_section: "section" },
      dimensions: {
        evidence: "evidence",
        clarity: "clarity",
        completeness: "completeness",
        boundary: "boundary",
        delivery: "delivery",
      },
    },
  },
  "zh-CN": {
    htmlLang: "zh-CN",
    nav: {
      today: "今日",
      plan: "计划",
      materials: "材料",
      practice: "练习",
      review: "复盘",
      import: "导入",
      library: "资料库",
    },
    common: {
      importThesis: "导入论文",
      noThesis: "还没有论文",
      noActiveThesis: "当前没有启用的论文。请先导入论文。",
      importFirst: "请先导入论文。",
      none: "—",
    },
    home: {
      noThesisBody: "导入论文后开始准备 viva 答辩。",
      recommendedNext: "建议下一步：",
      fullPlan: "查看完整计划 →",
      dayOf: (day: number, total: number) => `第 ${day} 天 / 共 ${total} 天`,
      verified: "已验证",
      needsReview: "待复核",
      practiceRuns: "练习次数",
      toReview: "待复盘",
      evidenceSummary: (evidence: number, prep: number) => `${evidence} 条证据单元 · ${prep} 条备考材料 · `,
      librarySettings: "资料库与设置",
    },
    actions: {
      generatePrepPack: "生成备考材料包",
      setupAi: "配置 AI 后生成备考材料包",
      startPractice: "开始练习",
      reviewWeak: (count: number) => `复盘 ${count} 个薄弱点`,
      practiceAnother: "再练一道题",
    },
    materials: {
      title: "备考材料",
      empty: "还没有备考材料。点击“生成备考材料包”来创建学习材料。",
      edit: "编辑",
      generate: "生成备考材料包",
      generating: "生成中...",
      generated: (count: number) => `已生成 ${count} 条材料。`,
      verifiedNote: (basis: string, value: string) =>
        `已验证：${basis || "证据"}${value ? `（${value}）` : ""}能在论文证据中找到依据。周边表述为 AI 生成。`,
    },
    importPage: {
      title: "导入论文",
      body: "粘贴 Markdown/纯文本，或上传 PDF。导入后会替换当前启用论文。",
      titleField: "标题",
      source: "来源",
      markdown: "Markdown",
      plainText: "纯文本",
      pdf: "PDF",
      pdfFile: "PDF 文件",
      content: "内容",
      submit: "导入",
      submitting: "导入中...",
    },
    editItem: {
      title: "编辑备考材料",
      note: (type: string) => `${type} · 保存时会用绑定证据重新校验。`,
      boundEvidence: "绑定证据",
      noEvidence: "没有绑定证据 - 这条材料无法标记为已验证。",
      claim: "断言",
      fixedClaim: "固定断言：",
      supportingQuote: "支持引文（必须逐字出现在上方绑定证据中）",
      value: "数值",
      unit: "单位",
      save: "保存并重新校验",
      cancel: "取消",
    },
    practice: {
      title: "答辩练习",
      begin: "先生成一道问题开始练习。",
      questionType: "问题类型",
      topic: "主题（可选）",
      topicPlaceholder: "例如：方法论、样本量",
      generateQuestion: "生成问题",
      generating: "生成中...",
      question: (kind: string) => `${kind}问题`,
      yourAnswer: "你的回答：",
      weakReasons: "薄弱维度低分原因",
      diagnosis: "诊断",
      rewrite: "建议改写",
      followUps: "追问",
      record: "🎤 录制回答",
      stop: "■ 停止",
      transcribing: "转写中...",
      answerPlaceholder: "输入你的回答...",
      answerPlaceholderStt: "输入你的回答，或先录音再编辑转写文本...",
      submit: "提交回答",
      scoring: "评分中...",
      recordUnsupported: "当前浏览器不支持录音，请改为手动输入。",
      noAudio: "没有捕获到音频。",
      tooLong: "录音太长，请控制在约 10 MB 以内。",
      transcribeFail: "无法转写录音，请重试。",
      micFail: "无法访问麦克风。",
      speechUnsupported: "当前浏览器不支持语音识别，请改为手动输入。",
      speechError: (error?: string) => `语音识别错误${error ? `：${error}` : ""}。`,
      speechStartFail: "无法启动语音识别。",
    },
    review: {
      title: "复盘队列",
      headline: "复盘",
      body: "得分 2 分及以下的维度值得再练一次。",
      practiceMore: "继续练习 →",
      empty: "当前没有待复盘内容。先回答一些练习题，或说明你已经清空队列。",
    },
    plan: {
      title: "训练计划",
      importBody: "导入论文后开始制定训练计划。",
      buildFor: (title: string) => `为“${title}”生成本地学习计划。`,
      days: "天数",
      generate: "生成计划",
      aiOn: "AI 已启用：生成计划会把论文标题、章节名和简短进度摘要发送给你配置的 AI 服务。",
      aiOff: "AI 已关闭：将生成标准 N 天模板，不会发送任何内容。",
      daySummary: (name: string, day: number, total: number) => `${name} · 第 ${day} 天 / 共 ${total} 天`,
      doubleCheck: "这是学习计划，请结合材料和备考包复核具体内容。",
      today: "今天",
      noPlan: "还没有训练计划",
      noPlanBody: "选择天数并生成计划，用它固定每天的备考节奏。",
      ai: "AI",
      static: "静态",
    },
    library: {
      title: "资料库与设置",
      activeThesis: "当前论文",
      titleField: "标题",
      author: "作者",
      source: "来源",
      imported: "导入时间",
      noImported: "还没有导入论文。",
      importOne: "导入一篇",
      yourTheses: "你的论文",
      active: "当前",
      makeActive: "设为当前",
      aiPrivacy: "AI 与隐私",
      aiLabel: "AI 考官 / 评审 / 材料生成：",
      sttLabel: "语音转文字：",
      aiEnabled:
        "已启用 - 内容会发送到你配置的 AI Gateway 提供方：生成备考包会发送论文标题和绑定证据；生成问题或评分会发送问题文本、相关证据和你的回答；追问还会包含上一题和上一轮回答。",
      aiGatewayMissing: "关闭 - 已设置 provider key，但未设置 AI_GATEWAY_API_KEY，因此不会发送内容。",
      aiDisabled: "已禁用 - 不会发送论文文本或回答。",
      sttOff: "关闭 - 不会捕获或发送音频。",
      sttBrowser: "浏览器 - 使用浏览器内置连续识别。根据浏览器不同，音频可能由浏览器厂商服务处理；音频不会经过本应用。",
      sttGoogle: "Google Cloud - 录音会发送到 Google Cloud Speech-to-Text。约 1 分钟以上的回答不适合这个模式。",
      localData: "你的论文、数据库和录音始终保存在本机。",
      nothingLeaves: " 在当前配置下，没有内容离开本机。",
      accuracy: "内容准确性",
      unsafe: "不安全",
      draft: "草稿",
      accuracyBody:
        "只有关键事实能被绑定证据确定性证明的备考材料才会标为已验证。其他内容保持待复核、不安全或草稿状态，本应用不会把未经验证的断言当作事实展示。",
      importStats: "导入论文后查看准确性统计。",
    },
    labels: {
      statuses: { verified: "已验证", needs_review: "待复核", unsafe: "不安全", draft: "草稿" },
      itemTypes: {
        digest: "摘要",
        key_number: "关键数字",
        qa: "问答",
        hostile: "刁钻问题",
        hostile_question: "刁钻问题",
        theory_card: "理论卡",
        citation_card: "引用卡",
      },
      support: { numeric: "数字", exact_quote: "引文", existence: "", llm_suggested: "" },
      questionKinds: { random: "随机", cross_section: "跨章节", hostile: "刁钻", boundary: "边界", by_section: "章节" },
      dimensions: {
        evidence: "证据",
        clarity: "清晰度",
        completeness: "完整性",
        boundary: "边界",
        delivery: "表达",
      },
    },
  },
} as const;

export function getUiCopy(locale: UiLocale) {
  return uiCopy[locale] ?? uiCopy.en;
}

export function normalizeUiLocale(value: string | undefined): UiLocale {
  return value === "zh-CN" ? "zh-CN" : "en";
}

export function labelFromMap(map: Record<string, string>, value: string): string {
  return map[value] ?? value.replaceAll("_", " ");
}
